### PR TITLE
Add Config Roles to Standard Config Files

### PR DESCRIPTION
**Pull request by coreyasmith**
Add config roles to standard config files so that it's no longer required to rename/delete standard config files at release time on Sitecore instances running Sitecore 9 or the [Sitecore Configuration Roles module](https://github.com/Sitecore/Sitecore-Configuration-Roles).

* `Unicorn.AutoPublish.config`: header says to remove from CD environments, so apply to only `Standalone` or `ContentManagement`.
* `Unicorn.config`: not needed.
* `Unicorn.Configs.Default.example`: not needed.
* `Unicorn.Configs.Dependency.config.example`: not needed.
* `Unicorn.Configs.NewItemsOnly.example`: not needed.
* `Unicorn.CustomSerializationFolder.config.example`: probably not needed.
* `Unicorn.DataProvider.config`: header says to remove from *any* deployed instance, so apply to only `Standalone`. I'm torn on this one since `Standalone` could mean either your local dev environment or a combined CM/CD environment. In the case of the latter, it probably shouldn't be enabled. 🤷‍♂️ 
* `Unicorn.Deployed.config.disabled`: header says to deploy to only CM environment, so apply only to `ContentManagement`. Torn on this one as well, because it should probably be enabled in combined CM/CD environments. Also, should we enable this one and expect users without config roles to delete/disable it in the appropriate environments going forward? 🤷‍♀️ 
* `Unicorn.Dilithium.config.example`: header says to apply to only local dev or CM environment, so apply to `Standalone` or `ContentManagement`.
* `Unicorn.PowerShell.config`: header says to apply to only local dev or CM environment, so apply to `Standalone` or `ContentManagement`.
* `Unicorn.Remote.config.disabled`: didn't bother since it only applies to local dev.
* `Unicorn.UI.config`: header says to remove from CD environments, so apply to only `Standalone` or `ContentManagement`.
* `Unicorn.zSharedSecret.config.example`: not needed.

I tested the `role:require="Standalone"` attribute in Sitecore 8.0, 8.1, and 8.2 instances without the Configuration Roles module installed and had no issues. As expected, Sitecore just ignores the attribute.

### CODE REVIEW

**Comment by AlenPelin** [comment]
Thanks for implementing this! Going through the changes ([Unicorn.DataProvider.config](https://github.com/SitecoreUnicorn/Unicorn/blob/ac4bd9a4855ed58e262f3c913c8fcebe75add524/src/Unicorn/Standard%20Config%20Files/Unicorn.DataProvider.config)) and comments above it seems that there is a bit of confusion that `Standalone` role means `Developer` installation. In certain particular cases it is true, however it is very often that `Standalone` instance may be in production environment and `ContentManagement and Processing and Reporting`  instance can be developer's one. 

Configuration Roles engine (from appropriate module and OOB Sitecore 9) is not a replacement for configuration files transformations.

**Comment by AlenPelin** [comment]
@coreyasmith I'd love to get your thoughts on that. I am thinking of how to come up with best way to fix it, so far I have only one thing in mind:
* Introduce `<add key="env:define" value="Development" />` in `web.config`
* In [Unicorn.DataProvider.config](https://github.com/SitecoreUnicorn/Unicorn/blob/ac4bd9a4855ed58e262f3c913c8fcebe75add524/src/Unicorn/Standard%20Config%20Files/Unicorn.DataProvider.config) use following in header:

```xml
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/"
  xmlns:role="http://www.sitecore.net/xmlconfig/role/" 
  xmlns:env="http://www.sitecore.net/xmlconfig/env/">
  <sitecore role:require="Standalone or ContentManagement" env:require="Development">
```

**Note**, it is kinda OOB feature:  see `/App_Config/Environment/Sitecore.PipelineProfiling.config`.

**Comment by coreyasmith** [comment]
@AlenPelin I didn't realize that `env` was already defined in `Sitecore.PipelineProfiling.config`--thanks for pointing that out. I agree with you, `Standalone` isn't a good fit for a lot of these configs.

I think you've got the right approach; it's certainly more correct than relying on `Standalone`. My only concern is that we'll need to educate users to patch `<add key="env:define" value="Development" />` into their `Web.config` for Unicorn to work locally. Thoughts @kamsar @cassidydotdk?

**Comment by cassidydotdk** [comment]
I'm no fan of anything needing an after-touch that cannot be delivered via NuGet. And since Sitecore does not work with the concept of a "Development" environment, whatever people want to do to work with these configuration roles, I feel is up to them. Unicorn is not the only piece of kit where special consideration has to be made, because `Standalone` is not synonymous with `Development`.

**Comment by coreyasmith** [comment]
So do we leave as is and add a note to the `README.md` and/or comments to the configs that users deploying to combined CM/CD instances should take care to set the config roles appropriate to their environment?

**Comment by cassidydotdk** [comment]
I'd say so. Will be part of the release notes that introduce the feature. But I'd say we should also see if we can influence things a bit, so that `Development` becomes a full citizen role inside the standard product. Is where every Sitecore solution is born, after all ;-)

**Comment by coreyasmith** [comment]
I 100% agree--it should be baked into the `Web.config` by default.

**Comment by kamsar** [comment]
No guarantees, but I passed along your idea to define the env in addition to role as it makes sense to have as a hook outside role.

**Pull request merged**
